---
title: "testing"
format: html
editor: visual
---

```{r}
library(viridis)   # colorblind friendly colors
library(patchwork) # put graphs together
library(spmodel)   # splm (spatial linear models)
library(ggplot2)
load("potato.RData")

summary(spatial_lm)
head(spatial_df)
```

Predictions
```{r}
# shared scale
min_val <- min(c(pred_grid_results$fit, pred_grid_results$lwr, pred_grid_results$upr), na.rm = TRUE)
max_val <- max(c(pred_grid_results$fit, pred_grid_results$lwr, pred_grid_results$upr), na.rm = TRUE)
shared_limits <- c(min_val, max_val)

fitplot <- ggplot(pred_grid_results, aes(x = POINT_X, y = POINT_Y)) +
  geom_point(aes(color = fit), size = 1) +
  scale_color_viridis_c(limits = shared_limits) + # Syncing here
  labs(title = "Predicted CWSI (Fit)", x = "X coord", y = "Y coord", color = "CWSI") +
  theme_minimal()

lwrplot <- ggplot(pred_grid_results, aes(x = POINT_X, y = POINT_Y)) +
  geom_point(aes(color = lwr), size = 1) +
  scale_color_viridis_c(limits = shared_limits) + # Syncing here
  labs(title = "Lower 95% Bound", x = "X coord", y = "Y coord", color = "CWSI") +
  theme_minimal()

uprplot <- ggplot(pred_grid_results, aes(x = POINT_X, y = POINT_Y)) +
  geom_point(aes(color = upr), size = 1) +
  scale_color_viridis_c(limits = shared_limits) + # Syncing here
  labs(title = "Upper 95% Bound", x = "X coord", y = "Y coord", color = "CWSI") +
  theme_minimal()

(fitplot / (lwrplot + uprplot)) + 
  plot_layout(heights = c(4, 2), guides = "collect")& 
  coord_fixed() & 
  theme(legend.position = "right")
```

